### ISSUE TITLE
returns buffer on AWS Lambda

### ISSUE THREAD

**Issue by sean256** [lovell/64#5]
I'm doing npm install with `docker run -v "$PWD":/var/task lambci/lambda:build-nodejs8.10 npm install`

```js
const base64 = require('64');

const responseFromBuffer = (buffer, { cacheTag, eTag }) => ({
	headers: {
		'Content-Type': 'image/jpeg',
	},
	isBase64Encoded: true,
	body: base64.encode(buffer),
});
...
...
```

The lambda logs show the output of body to be

```
"body":{"type":"Buffer","data":[105,86,66,79,82,119,48...
```

**Comment by lovell** [comment]
Hello, the [encode](https://github.com/lovell/64#encodeinput) function "Returns a Buffer containing the Base64 encoded version of input."

For String output, try something like the following:

```diff
- body: base64.encode(buffer),
+ body: base64.encode(buffer).toString('ascii'),
```

**Comment by sean256** [comment]
oh duh, thank you
